# Generated by Django 5.2 on 2025-05-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="battery",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="batch",
            name="capacity",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="batch",
            name="device_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
