# Generated by Django 5.2 on 2025-10-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testanswer",
            name="technical_output",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
