# Generated by Django 5.2 on 2025-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_testanswer_technical_output"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalOutputChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="e.g., 200W, 1700W, 300A", max_length=50, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["order", "value"],},
        ),
    ]
