# Generated by Django 5.2 on 2025-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0004_batchspectemplate_batch_current_max_batch_dc_load_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="batch", name="battery",),
        migrations.AlterField(
            model_name="batch",
            name="device_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
