# Generated by Django 5.2 on 2025-10-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_batch_battery_alter_batch_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="battery",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
